//  Copyright (c) 2014, Rob J Meijer
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
#ifndef _RUMPELSTILTSKIN_HPP
#define _RUMPELSTILTSKIN_HPP
#include <string>
#include <memory>
#include <inttypes.h>
namespace rumpelstiltskin {
  struct Node;
  struct Server;
  struct AbstractServer;
  struct AbstractNode {
      virtual std::string rocap() const  = 0;  // Get the sparsecap for read-only access.
      virtual std::string rwcap() const = 0; //Get the sparse-cap for unatenuated access.
      virtual std::string location() const = 0; //Get the relative path where this node would have to be serialized.
      virtual uint8_t const * const rawkey() const = 0; //Get raw pointer to the binary crypto key to use for serialisation.
      virtual bool is_attenuated() const = 0; //Query if this node is unatenuated or read only.
  };
  struct Node : public AbstractNode {
      Node(AbstractNode *,AbstractServer const *);
      std::string rocap() const ;
      std::string rwcap() const ;
      std::string location() const ;
      uint8_t const * const rawkey() const;
      Node operator[](std::string) const ; //Convenience method for getting at child node using weak name.
      bool is_attenuated() const;
      Node attenuated() const;
    private:
      std::unique_ptr<AbstractNode> pImpl;
      AbstractServer const *sServer;
  };
  struct AbstractServer {
      virtual Node operator[](std::string) const = 0; //Get a Node from a sparse-cap string.
      virtual Node operator()(Node const *, std::string) const= 0; //Get a child node using a weak name and a parent node.
      virtual Node attenuated(Node const *) const = 0;
  };
  struct Server: public AbstractServer {
      Server(AbstractServer *s);
      Node operator[](std::string) const;
      Node operator()(Node const *, std::string) const;
      Node attenuated(Node const *) const;
    private:
      std::unique_ptr<AbstractServer> pImpl;
  };
  //Function for creating a server object using one or two secrets. Use one secret for local storage or two
  //if you are using any kind of network storage server or service as underlying place to do serialization.
  Server create_server(std::string mainsecret, std::string cloudsecret="local");
  //Turn a password of kinds into a suitable root cap for a tree.
  std::string pass2rootcap(std::string pass);
  //Get a securely random suitable root cap for a tree.
  std::string randomrootcap();
  //Get a securely random secret usable as argument for create_server
  std::string randomsecret();
}
#endif
